version: "3"

services:
  app:
    build: .

    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/go/src/prueba
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
