version: "3"

services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      PORT: 3000
      API_KEY: "your_api_key"
      DB_HOST: "yor_uri_host_for_connect"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "your_username"
      MONGO_INITDB_ROOT_PASSWORD: "your_password"
